/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotapp

import org.amshove.kluent.shouldBe
import org.junit.jupiter.api.Test



class AppTest {
    @Test
    fun `hello world`() {
        val x = 10
        x shouldBe 10
    }
}
