/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotapp

import io.ktor.application.*
import io.ktor.features.CallLogging
import io.ktor.features.DefaultHeaders
import io.ktor.http.*
import io.ktor.response.*
import io.ktor.routing.*
import io.ktor.server.engine.*
import io.ktor.server.netty.*
import kotapp.api.Health


fun Application.main() {
    install(DefaultHeaders)
    install(CallLogging)
    install(Routing) {
        get("/") {
            call.respondText("My Example Blog2", ContentType.Text.Html)
        }

        Health()
    }
}

/*
fun main(args: Array<String>) {
    embeddedServer(Netty, commandLineEnvironment(args)).start()
}
*/